#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Riyan_Restaurant.Resource", IsApplication=true)]

namespace Riyan_Restaurant
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int back = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int menu_1 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int menuitem_1 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int menuitem_2 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int menuitem_3 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int menuitem_4 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int menuitem_5 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int menuitem_6 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int r_logo = 2130837513;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int BookButton = 2131034115;
			
			// aapt resource value: 0x7f050009
			public const int Button1 = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int Button2 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int Button3 = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int Button4 = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int Button5 = 2131034125;
			
			// aapt resource value: 0x7f050006
			public const int ConfirmButton = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int FeedbackButton = 2131034117;
			
			// aapt resource value: 0x7f050007
			public const int PayButton = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int galleryview = 2131034116;
			
			// aapt resource value: 0x7f050001
			public const int imageView1 = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int imageview1 = 2131034120;
			
			// aapt resource value: 0x7f050002
			public const int textView1 = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int textviewlabel = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int layout1 = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int layout2 = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int layout3 = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int layout4 = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int layout5 = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int layout6 = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Main = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
